name: Python Tests

on: [push]

jobs:
  build:
    runs-on: python:3.10

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: pip3 install poetry && poetry install

      - name: Test with pytest
        run: pytest --workers auto --tests-per-worker auto
