name: Python Tests

on: [push]

jobs:
  build:
    runs-on: registry.lunes.io/blockchain/production/lunespy

    steps:
    - name: Get latest code
    - uses: actions/checkout@v2

    - name: Test with pytest
      run: pytest --workers auto --tests-per-worker auto
