name: Python Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Test with pytest
      run: pytest --workers auto --tests-per-worker auto
